# Generated by Django 6.0 on 2025-12-29 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('regulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancestep',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='compliance.compliancechecklist'),
        ),
        migrations.AddField(
            model_name='compliancestep',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulations.regulation'),
        ),
    ]
