# Generated by Django 6.0.5 on 2026-05-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancestep_completed_at_compliancestep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecklist',
            name='business_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
