# Generated by Django 6.0 on 2026-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='revenue',
            field=models.CharField(choices=[('0_10', '0M - 10M NPR'), ('10_30', '10M - 30M NPR'), ('30_50', '30M - 500M NPR'), ('50_100', '50M - 100M NPR'), ('100_plus', '100M+ NPR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('public_limited', 'Public Limited')], max_length=50),
        ),
    ]
