# Generated by Django 6.0 on 2025-12-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='regulations/')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('business_action', models.CharField(max_length=100)),
                ('mapping_logic', models.TextField()),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.regulation')),
            ],
        ),
    ]
